export const RESOLVE_USER = 'RESOLVE_USER';
export const RESOLVE_SURVEYS = 'RESOLVE_SURVEYS';
export const RESOLVE_SURVEY = 'RESOLVE_SURVEY';
export const REMOVE_SURVEY = 'REMOVE_SURVEY';
export const UPDATE_SORT_BY = 'UPDATE_SORT_BY';
export const UPDATE_FILTER = 'UPDATE_FILTER';