export const RESOLVE_USER = 'RESOLVE_USER';
export const RESOLVE_SURVEYS = 'RESOLVE_SURVEYS';
export const RESOLVE_SURVEY = 'RESOLVE_SURVEY';
export const REMOVE_SURVEY = 'REMOVE_SURVEY';
export const RESOLVE_SORT_BY = 'RESOLVE_SORT_BY';